# Generated by Django 6.0.7 on 2026-09-17 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_otp_options_workspace_workspace_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='54d336', max_length=6),
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('animated', models.BooleanField(default=True)),
                ('source', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=40)),
                ('targetHandle', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
