# Generated by Django 6.0.7 on 2026-09-18 23:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_otp_otp_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='position',
            field=models.JSONField(default=core.models._default_position),
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.JSONField(default=core.models._default_position),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.JSONField(default=core.models._default_position),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='bedd8a', max_length=6),
        ),
    ]
